config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :lectures
  get 'hey/there'
  resources :courses do
    member do
      get "addlecture"
      post "startcourse"
    end
  end
  resources :othercats
  resources :cats, path: "cat"
  get "featuredskill", to: 'featuredskill#hey'
  get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: %i[ show edit update destroy ]

  # GET /lectures or /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1 or /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures or /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to lecture_url(@lecture), notice: "Lecture was successfully created." }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1 or /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to lecture_url(@lecture), notice: "Lecture was successfully updated." }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1 or /lectures/1.json
  def destroy
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to lectures_url, notice: "Lecture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lecture_params
      params.require(:lecture).permit(:course_id, :text)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture) do |form| %>
  <% if lecture.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
        <% lecture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.number_field :course_id %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/_lecture.html.erb
<div id="<%= dom_id lecture %>">
  <p>
    <strong>Course:</strong>
    <%= lecture.course_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= lecture.text %>
  </p>

</div>

app/views/lectures/edit.html.erb
<h1>Editing lecture</h1>

<%= render "form", lecture: @lecture %>

<br>

<div>
  <%= link_to "Show this lecture", @lecture %> |
  <%= link_to "Back to lectures", lectures_path %>
</div>

app/views/lectures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lectures</h1>

<div id="lectures">
  <% @lectures.each do |lecture| %>
    <%= render lecture %>
    <p>
      <%= link_to "Show this lecture", lecture %>
    </p>
  <% end %>
</div>

<%= link_to "New lecture", new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New lecture</h1>

<%= render "form", lecture: @lecture %>

<br>

<div>
  <%= link_to "Back to lectures", lectures_path %>
</div>

app/views/lectures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lecture %>

<div>
  <%= link_to "Edit this lecture", edit_lecture_path(@lecture) %> |
  <%= link_to "Back to lectures", lectures_path %>

  <%= button_to "Destroy this lecture", @lecture, method: :delete %>
</div>