config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :lectures
  get 'hey/there'
  resources :courses do
    member do
      get "addlecture"
      post "startcourse"
    end
  end
  resources :othercats
  resources :cats, path: "cat"
  get "featuredskill", to: 'featuredskill#hey'
  get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/othercat.rb
class Othercat < ApplicationRecord
end

app/controllers/othercats_controller.rb
class OthercatsController < ApplicationController
  before_action :set_othercat, only: %i[ show edit update destroy ]

  # GET /othercats or /othercats.json
  def index
    @othercats = Othercat.all
  end

  # GET /othercats/1 or /othercats/1.json
  def show
  end

  # GET /othercats/new
  def new
    @othercat = Othercat.new
  end

  # GET /othercats/1/edit
  def edit
  end

  # POST /othercats or /othercats.json
  def create
    @othercat = Othercat.new(othercat_params)

    respond_to do |format|
      if @othercat.save
        format.html { redirect_to othercat_url(@othercat), notice: "Othercat was successfully created." }
        format.json { render :show, status: :created, location: @othercat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @othercat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /othercats/1 or /othercats/1.json
  def update
    respond_to do |format|
      if @othercat.update(othercat_params)
        format.html { redirect_to othercat_url(@othercat), notice: "Othercat was successfully updated." }
        format.json { render :show, status: :ok, location: @othercat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @othercat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /othercats/1 or /othercats/1.json
  def destroy
    @othercat.destroy

    respond_to do |format|
      format.html { redirect_to othercats_url, notice: "Othercat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_othercat
      @othercat = Othercat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def othercat_params
      params.require(:othercat).permit(:name, :description)
    end
end

app/helpers/othercats_helper.rb
module OthercatsHelper
end

app/views/othercats/_form.html.erb
<%= form_with(model: othercat) do |form| %>
  <% if othercat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(othercat.errors.count, "error") %> prohibited this othercat from being saved:</h2>

      <ul>
        <% othercat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/othercats/_othercat.html.erb
<div id="<%= dom_id othercat %>">
  <p>
    <strong>Name:</strong>
    <%= othercat.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= othercat.description %>
  </p>

</div>

app/views/othercats/edit.html.erb
<h1>Editing othercat</h1>

<%= render "form", othercat: @othercat %>

<br>

<div>
  <%= link_to "Show this othercat", @othercat %> |
  <%= link_to "Back to othercats", othercats_path %>
</div>

app/views/othercats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Othercats</h1>

<div id="othercats">
  <% @othercats.each do |othercat| %>
    <%= render othercat %>
    <p>
      <%= link_to "Show this othercat", othercat %>
    </p>
  <% end %>
</div>

<%= link_to "New othercat", new_othercat_path %>

app/views/othercats/new.html.erb
<h1>New othercat</h1>

<%= render "form", othercat: @othercat %>

<br>

<div>
  <%= link_to "Back to othercats", othercats_path %>
</div>

app/views/othercats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @othercat %>

<div>
  <%= link_to "Edit this othercat", edit_othercat_path(@othercat) %> |
  <%= link_to "Back to othercats", othercats_path %>

  <%= button_to "Destroy this othercat", @othercat, method: :delete %>
</div>