config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :lectures
  get 'hey/there'
  resources :courses do
    member do
      get "addlecture"
      post "startcourse"
    end
  end
  resources :othercats
  resources :cats, path: "cat"
  get "featuredskill", to: 'featuredskill#hey'
  get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :somecats
  has_many :course_have_somecats, through: :somecats, source: :somecats
  has_many :courses, -> { distinct }, through: :somecats
    def popular
      Course.joins(:votes,:somecats).select("courses.*, avg(cast(votes.note as float)) as myvalue,count(distinct votes.id) as numvotes").group("courses.id").having((["myvalue > ? and somecats.id in (#{somecats.map{|h|"?"}.join(",")}) and numvotes > 20", 2]+self.somecat_ids))
            end
      def trendingnew
        Course.joins(:votes,:somecats).select("courses.*, avg(cast(votes.note as float)) as myvalue").group("courses.id").having((["courses.created_at > ? and myvalue > ? and somecats.id in (#{somecats.map{|h|"?"}.join(",")})",1.months.ago, 3]+self.somecat_ids))
              end
      def self.search(x)
        Course.left_joins(:somecats).where("(select count(distinct x.somecat_id) from course_have_somecats x where x.somecat_id in (#{x.join(",")})) >= #{x.length} and courses.id in (select (x.course_id) from course_have_somecats x where x.somecat_id in (#{x.join(",")}) and courses.id = x.course_id) ").distinct
      end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :course_have_somecats
  has_many :user_start_courses
  has_many :somecats, through: :course_have_somecats

  #has_and_belongs_to_many :somecats, :join_table => :course_have_somecats

  def catid
    course_have_somecats[0].cat.id
  end
  has_many :lectures
  has_many :votes
  accepts_nested_attributes_for :lectures, allow_destroy: true
  before_validation do
     errors.add(:somecats, "sélectionner 1 ou plusieurs catégories") if self.somecats.length == 0
  end
  def hours
    self.nbminutes.to_i/60.to_i
  end
  def self.popular
    Course.joins(:votes).select("courses.*, avg(cast(votes.note as float)) as myvalue").group("courses.id").having("myvalue > ?", 3)
  end
  def self.trendingnew
    Course.joins(:votes).select("courses.*, avg(cast(votes.note as float)) as myvalue").group("courses.id").having("courses.created_at > ? and myvalue > ?",1.months.ago, 3)
  end
  def note
    Course.joins(:votes).select("courses.*, avg(cast(votes.note as float)) as myvalue").group("courses.id").having("courses.id = ?",self.id)[0].myvalue.to_i
  rescue
    5
  end
end

app/models/course_have_somecat.rb
class CourseHaveSomecat < ApplicationRecord
  belongs_to :course

  belongs_to :somecat
  has_one :cat, through: :somecat
  
end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/othercat.rb
class Othercat < ApplicationRecord
end

app/models/somecat.rb
class Somecat < ApplicationRecord
  belongs_to :cat
  has_many :course_have_somecats
     has_many :courses, through: :course_have_somecats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def self.find_for_database_authentication(conditions={})
      find_by(username: conditions[:email]) || find_by(email: conditions[:email])
  end
end

app/models/user_start_course.rb
class UserStartCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
  validates_uniqueness_of :user_id, scope: :course_id
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :course
  validates_uniqueness_of :user_id, scope: :course_id
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  # GET /cats or /cats.json
  def course
    @course=Cat.search(params[:myids])
    render layout: false
  end
  def index
    @cats = Cat.all
  end

  # GET /cats/1 or /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats or /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully created." }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1 or /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully updated." }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1 or /cats/1.json
  def destroy
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to cats_url, notice: "Cat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:name, :description)
    end
end

app/controllers/hey_controller.rb
class HeyController < ApplicationController
  def there
    render json: {heythere: Somecat.where(cat_id: params[:id])}.as_json, layout: false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: %i[ show edit update destroy ]
  protect_from_forgery except: [:create]

  # GET /votes or /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1 or /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes or /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to vote_url(@vote), notice: "Vote was successfully created." }
        format.json { render :show, status: :created, location: @vote,layout: false }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1 or /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to vote_url(@vote), notice: "Vote was successfully updated." }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1 or /votes/1.json
  def destroy
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url, notice: "Vote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vote_params
      params.require(:vote).permit(:course_id, :user_id, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/featuredskill_helper.rb
module FeaturedskillHelper
end

app/helpers/hey_helper.rb
module HeyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/othercats_helper.rb
module OthercatsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/cats/_cat.html.erb
<div id="<%= dom_id cat %>">
  <p>
    <strong>Name:</strong>
    <%= cat.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= cat.description %>
  </p>

</div>

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/course.html.erb
<%=render partial: "courses/mycourse", as: :course, collection: @course%>

app/views/cats/edit.html.erb
<h1>Editing cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Show this cat", @cat %> |
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cats</h1>

<div id="cats">
  <% @cats.each do |cat| %>
    <%= render cat %>
    <p>
      <%= link_to "Show this cat", cat %>
    </p>
  <% end %>
</div>

<%= link_to "New cat", new_cat_path %>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @cat.name %></h1>
<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
              <button class="nav-link active" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">nouveau et dans les tendances</button>
          <button class="nav-link" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">le plus populaiore</button>

                        </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
    <%=@cat.trendingnew.length > 0 ? (render @cat.trendingnew) : "pas de cours populaires en ce moment"%>
  </div>
  <div class="tab-pane fade " id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
    <%=@cat.popular.length > 0 ? (render @cat.popular) : "pas de cours populaires en ce moment"%>
  </div>

</div>
<div id="div1">
<div class="class1">
<%@cat.somecats.each do |hey|%>
  <%=label_tag "checkbox"+hey.id.to_s, hey.name do%>
    <%=hey.name%>
  <%=check_box_tag 'heycat', hey.id, false, id:"checkbox"+hey.id.to_s%>
<%end%>

<%end%>
</div>
<div class="">
  <div class="class2 row row-cols-1 row-cols-md-2 g-4">
    <%=render @cat.courses.limit(5)%>
  </div>
</div>
</div>


<div>
  <%= link_to "Edit this cat", edit_cat_path(@cat) %> |
  <%= link_to "Back to cats", cats_path %>

  <%= button_to "Destroy this cat", @cat, method: :delete %>
</div>

app/views/votes/_form.html.erb
<%= form_with(model: vote) do |form| %>
  <% if vote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
        <% vote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.number_field :course_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :note, style: "display: block" %>
    <%= form.text_field :note %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/_vote.html.erb
<div id="<%= dom_id vote %>">
  <p>
    <strong>Course:</strong>
    <%= vote.course_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= vote.user_id %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= vote.note %>
  </p>

</div>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render "form", vote: @vote %>

<br>

<div>
  <%= link_to "Show this vote", @vote %> |
  <%= link_to "Back to votes", votes_path %>
</div>

app/views/votes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Votes</h1>

<div id="votes">
  <% @votes.each do |vote| %>
    <%= render vote %>
    <p>
      <%= link_to "Show this vote", vote %>
    </p>
  <% end %>
</div>

<%= link_to "New vote", new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render "form", vote: @vote %>

<br>

<div>
  <%= link_to "Back to votes", votes_path %>
</div>

app/views/votes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vote %>

<div>
  <%= link_to "Edit this vote", edit_vote_path(@vote) %> |
  <%= link_to "Back to votes", votes_path %>

  <%= button_to "Destroy this vote", @vote, method: :delete %>
</div>